#pragma once

#include "mem_write_info.hpp"

namespace debug {
    constexpr MemWriteInfo mem_write_table[256] = {
        /* 0x00 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x01 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x02 */ { 1, {
                            { MemAddrSrc::BC, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x03 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x04 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x05 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x06 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x07 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x08 */ { 2, {
                            { MemAddrSrc::WZ, 1 },
                            { MemAddrSrc::WZ, 1 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x09 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x0A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x0B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x0C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x0D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x0E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x0F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x10 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x11 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x12 */ { 1, {
                            { MemAddrSrc::DE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x13 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x14 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x15 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x16 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x17 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x18 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x19 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x1A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x1B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x1C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x1D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x1E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x1F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x20 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x21 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x22 */ { 1, {
                            { MemAddrSrc::HL, 1 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x23 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x24 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x25 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x26 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x27 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x28 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x29 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x2A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x2B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x2C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x2D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x2E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x2F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x30 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x31 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x32 */ { 1, {
                            { MemAddrSrc::HL, -1 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x33 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x34 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x35 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x36 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x37 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x38 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x39 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x3A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x3B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x3C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x3D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x3E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x3F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x40 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x41 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x42 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x43 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x44 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x45 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x46 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x47 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x48 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x49 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x4A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x4B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x4C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x4D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x4E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x4F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x50 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x51 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x52 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x53 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x54 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x55 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x56 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x57 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x58 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x59 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x5A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x5B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x5C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x5D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x5E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x5F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x60 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x61 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x62 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x63 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x64 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x65 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x66 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x67 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x68 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x69 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x6A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x6B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x6C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x6D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x6E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x6F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x70 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x71 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x72 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x73 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x74 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x75 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x76 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x77 */ { 1, {
                            { MemAddrSrc::HL, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x78 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x79 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x7A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x7B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x7C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x7D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x7E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x7F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x80 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x81 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x82 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x83 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x84 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x85 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x86 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x87 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x88 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x89 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x8A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x8B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x8C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x8D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x8E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x8F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x90 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x91 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x92 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x93 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x94 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x95 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x96 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x97 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x98 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x99 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x9A */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x9B */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x9C */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x9D */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x9E */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0x9F */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA0 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA1 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA2 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA3 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA4 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA5 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA6 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA7 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA8 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xA9 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xAA */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xAB */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xAC */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xAD */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xAE */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xAF */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB0 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB1 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB2 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB3 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB4 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB5 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB6 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB7 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB8 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xB9 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xBA */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xBB */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xBC */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xBD */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xBE */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xBF */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC0 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC1 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC2 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC3 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC4 */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC5 */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC6 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC7 */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC8 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xC9 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xCA */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xCB */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xCC */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xCD */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xCE */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xCF */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD0 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD1 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD2 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD3 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD4 */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD5 */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD6 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD7 */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD8 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xD9 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xDA */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xDB */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xDC */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xDD */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xDE */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xDF */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE0 */ { 1, {
                            { MemAddrSrc::FF_Z, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE1 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE2 */ { 1, {
                            { MemAddrSrc::FF_C, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE3 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE4 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE5 */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE6 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE7 */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE8 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xE9 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xEA */ { 1, {
                            { MemAddrSrc::WZ, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xEB */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xEC */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xED */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xEE */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xEF */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF0 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF1 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF2 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF3 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF4 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF5 */ { 2, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF6 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF7 */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF8 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xF9 */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xFA */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xFB */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xFC */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xFD */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xFE */ { 0, {
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } },
        /* 0xFF */ { 3, {
                            { MemAddrSrc::SP, -1 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::SP, 0 },
                            { MemAddrSrc::NONE, 0 },
                        } }
    };
} // namespace debug
